version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://app_user:securepassword@db:5432/dating_app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: dating_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: